// Generated by CoffeeScript 1.6.2
$(function() {
  var execAfterLoading, removeSelectors, removeSelectorsById, removedFriendsYouMayKnow;

  removeSelectorsById = function(selectors) {
    return removeSelectors(selectors.map(function(selector) {
      return document.getElementById(selector);
    }));
  };
  removeSelectors = function(selectors) {
    return selectors.forEach(function(selector) {
      return $(selector).remove();
    });
  };
  removeSelectorsById(['pagelet_ego_pane', 'pagelet_ego_contextual_group', 'topnews_main_stream_408239535924329']);
  execAfterLoading = function(testBoolean, existenceSelector, fn) {
    var tid, tryAgain;

    tid = void 0;
    if (!testBoolean) {
      tryAgain = function() {
        if (existenceSelector) {
          fn();
          testBoolean = true;
          return clearInterval(tid);
        } else {
          console.log("Trying to remove friends");
          return tid = setTimeout(tryAgain, 100);
        }
      };
      tid = setTimeout(tryAgain, 100);
    }
    return testBoolean;
  };
  removedFriendsYouMayKnow = false;
  return fbRequestsJewel.onclick = function() {
    return execAfterLoading(removedFriendsYouMayKnow, document.getElementById("fbRequestsPYMKContainer"), function() {
      console.log("Removing friends");
      removeSelectorsById(["fbRequestsPYMKContainer", "fbRequestsPYMLContainer"]);
      return $(document.getElementsByClassName("jewelWithEgoUnits")[0]).removeAttr("style");
    });
  };
});
