// Generated by CoffeeScript 1.6.2
$(function() {
  var didScroll, removeGarbage, removedFriends;

  didScroll = void 0;
  removeGarbage = void 0;
  removedFriends = void 0;
  removedFriends = false;
  removeGarbage = function() {
    $("span.uiStreamAdditionalLogging a").each(function() {
      if ($(this).html() === "Sponsored") {
        return $(this).closest(".uiUnifiedStory").css("display", "none");
      }
    });
    $("#pagelet_ego_pane").remove();
    $("#pagelet_ego_contextual_group").remove();
    fbRequestsJewel.onclick = function() {
      var removeFriends, tid;

      removeFriends = void 0;
      tid = void 0;
      console.log("Clicking friend request");
      if (removedFriends === false) {
        removeFriends = function() {
          tid = void 0;
          if (document.getElementById("fbRequestsPYMKContainer")) {
            console.log("Removing friends");
            $(document.getElementById("fbRequestsPYMKContainer")).remove();
            $(document.getElementById("fbRequestsPYMLContainer")).remove();
            $(document.getElementsByClassName("jewelWithEgoUnits")[0]).removeAttr("style");
            removedFriends = true;
            return clearInterval(tid);
          } else {
            console.log("Trying to remove friends");
            return tid = setTimeout(removeFriends, 100);
          }
        };
        return tid = setTimeout(removeFriends, 100);
      }
    };
    return $("#topnews_main_stream_408239535924329").remove();
  };
  removeGarbage();
  didScroll = false;
  return $(window).scroll(function() {
    var timer;

    timer = void 0;
    if (!didScroll) {
      timer = setInterval(function() {
        if (didScroll) {
          didScroll = false;
          clearTimeout(timer);
          return removeGarbage();
        }
      }, 250);
    }
    return didScroll = true;
  });
});
