// Generated by CoffeeScript 1.6.2
$(function() {
  var removeSelectors, removedFriendsYouMayKnow;

  removeSelectors = function(selectors) {
    return selectors.forEach(function(selector) {
      return $(document.getElementById(selector)).remove();
    });
  };
  $("#pagelet_ego_pane").remove();
  $("#pagelet_ego_contextual_group").remove();
  removedFriendsYouMayKnow = false;
  return fbRequestsJewel.onclick = function() {
    var removeFriends, tid;

    tid = void 0;
    if (!removedFriendsYouMayKnow) {
      removeFriends = function() {
        tid = void 0;
        if (document.getElementById("fbRequestsPYMKContainer")) {
          console.log("Removing friends");
          removeSelectors(["fbRequestsPYMKContainer", "fbRequestsPYMLContainer"]);
          $(document.getElementsByClassName("jewelWithEgoUnits")[0]).removeAttr("style");
          removedFriendsYouMayKnow = true;
          return clearInterval(tid);
        } else {
          console.log("Trying to remove friends");
          return tid = setTimeout(removeFriends, 100);
        }
      };
      tid = setTimeout(removeFriends, 100);
    }
    return $("#topnews_main_stream_408239535924329").remove();
  };
});
